In [5]:
 pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.9.1-cp39-cp39-win_amd64.whl (444.0 MB)
Collecting absl-py>=1.0.0
  Downloading absl_py-1.2.0-py3-none-any.whl (123 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.26.0-cp39-cp39-win_amd64.whl (1.5 MB)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Collecting protobuf<3.20,>=3.9.2
Note: you may need to restart the kernel to use updated packages.  Downloading protobuf-3.19.4-cp39-cp39-win_amd64.whl (895 kB)
Collecting tensorflow-estimator<2.10.0,>=2.9.0rc0
  Downloading tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
Requirement already satisfied: numpy>=1.20 in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (1.20.3)
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)

Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting keras<2.10.0,>=2.9.0rc0
  Downloading keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
Requirement already satisfied: h5py>=2.9.0 in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (3.2.1)
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting tensorboard<2.10,>=2.9
  Downloading tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
Collecting flatbuffers<2,>=1.12
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting libclang>=13.0.0
  Downloading libclang-14.0.6-py2.py3-none-win_amd64.whl (14.2 MB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.47.0-cp39-cp39-win_amd64.whl (3.6 MB)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (58.0.4)
Requirement already satisfied: packaging in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (21.0)
Requirement already satisfied: six>=1.12.0 in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\mstas\anaconda3\lib\site-packages (from tensorflow) (3.10.0.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\mstas\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.0)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.11.0-py2.py3-none-any.whl (167 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\mstas\anaconda3\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.26.0)
Collecting markdown>=2.6.8
  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\mstas\anaconda3\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.0.2)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\mstas\anaconda3\lib\site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (4.8.1)
Requirement already satisfied: zipp>=0.5 in c:\users\mstas\anaconda3\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (3.6.0)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\mstas\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mstas\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mstas\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mstas\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2021.10.8)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\mstas\anaconda3\lib\site-packages (from packaging->tensorflow) (3.0.4)
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=5991f3186d5d5d77cf7bc78a7de3ea6a56ffe73f2ead8b2ff4b2535d23abe08c
  Stored in directory: c:\users\mstas\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor
Installing collected packages: pyasn1, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, tensorboard-plugin-wit, tensorboard-data-server, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard, opt-einsum, libclang, keras-preprocessing, keras, google-pasta, gast, flatbuffers, astunparse, tensorflow
Successfully installed absl-py-1.2.0 astunparse-1.6.3 cachetools-5.2.0 flatbuffers-1.12 gast-0.4.0 google-auth-2.11.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.47.0 keras-2.9.0 keras-preprocessing-1.1.2 libclang-14.0.6 markdown-3.4.1 oauthlib-3.2.0 opt-einsum-3.3.0 protobuf-3.19.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.9.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.9.1 tensorflow-estimator-2.9.0 tensorflow-io-gcs-filesystem-0.26.0 termcolor-1.1.0

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import pandas as pd

In [32]:
url = url = 'C:\\Users\\mstas\\Desktop\\Deep-Learning-Homework\\resources\\charity_data.csv'
charity_df = pd.read_csv(url)
charity_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [33]:
charity_df = charity_df.drop(columns = ['EIN', 'NAME'],axis=0)
for x in charity_df.columns:
    print(x, len(charity_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [34]:
counts = charity_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [35]:
# replacement list

application_types_to_replace = list(counts[counts < 700].index)
application_types_to_replace

['T10', 'T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [36]:
# new df

for app in application_types_to_replace:
    charity_df['APPLICATION_TYPE'] = charity_df['APPLICATION_TYPE'].replace(app,"Other")
charity_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [37]:
counts_for_binning = charity_df['CLASSIFICATION'].value_counts()

In [39]:
classification_counts = counts_for_binning[counts_for_binning > 1]
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [40]:
classifications_to_replace = list (counts_for_binning[counts_for_binning < 100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [41]:
for cls in classifications_to_replace:
    charity_df['CLASSIFICATION'] = charity_df['CLASSIFICATION'].replace(cls,"Other")
charity_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [42]:
charity_df = pd.get_dummies(charity_df,dtype=float)
charity_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [43]:
y = charity_df['IS_SUCCESSFUL'].values
y

X = charity_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1.0000000e+00, 5.0000000e+03, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0859000e+05, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.6500179e+07, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

In [44]:

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [45]:
scaler = StandardScaler()

In [46]:
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [47]:
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14

In [48]:
nn = tf.keras.models.Sequential()

In [49]:
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

In [50]:
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

In [51]:
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 343

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 470
Trainable params: 470
Non-trainable params: 0
_________________________________________________________________

In [52]:
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 4s 4ms/step - loss: 0.6137 - accuracy: 0.6904 - val_loss: 0.5608 - val_accuracy: 0.7256
Epoch 2/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5697 - accuracy: 0.7182 - val_loss: 0.5549 - val_accuracy: 0.7297
Epoch 3/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5633 - accuracy: 0.7196 - val_loss: 0.5530 - val_accuracy: 0.7344
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5596 - accuracy: 0.7218 - val_loss: 0.5515 - val_accuracy: 0.7321
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5577 - accuracy: 0.7237 - val_loss: 0.5502 - val_accuracy: 0.7315
Epoch 6/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5559 - accuracy: 0.7251 - val_loss: 0.5481 - val_accuracy: 0.7318
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5548 - accuracy: 0.7266 - val_loss: 0.5477 - val_accuracy: 0.7349
Epoch 8/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5540 - accuracy: 0.7273 - val_loss: 0.5486 - val_accuracy: 0.7346
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5534 - accuracy: 0.7282 - val_loss: 0.5476 - val_accuracy: 0.7331
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5525 - accuracy: 0.7289 - val_loss: 0.5454 - val_accuracy: 0.7344
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7282 - val_loss: 0.5463 - val_accuracy: 0.7357
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7299 - val_loss: 0.5442 - val_accuracy: 0.7344
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7290 - val_loss: 0.5441 - val_accuracy: 0.7352
Epoch 14/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7296 - val_loss: 0.5448 - val_accuracy: 0.7357
Epoch 15/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7294 - val_loss: 0.5448 - val_accuracy: 0.7352
Epoch 16/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5494 - accuracy: 0.7285 - val_loss: 0.5449 - val_accuracy: 0.7359
Epoch 17/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7304 - val_loss: 0.5453 - val_accuracy: 0.7352
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7308 - val_loss: 0.5446 - val_accuracy: 0.7341
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7297 - val_loss: 0.5454 - val_accuracy: 0.7352
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5480 - accuracy: 0.7303 - val_loss: 0.5457 - val_accuracy: 0.7352
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7303 - val_loss: 0.5440 - val_accuracy: 0.7346
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5480 - accuracy: 0.7300 - val_loss: 0.5472 - val_accuracy: 0.7334
Epoch 23/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5479 - accuracy: 0.7314 - val_loss: 0.5461 - val_accuracy: 0.7349
Epoch 24/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7308 - val_loss: 0.5452 - val_accuracy: 0.7375
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7314 - val_loss: 0.5455 - val_accuracy: 0.7362
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7319 - val_loss: 0.5471 - val_accuracy: 0.7357
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7318 - val_loss: 0.5451 - val_accuracy: 0.7315
Epoch 28/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5469 - accuracy: 0.7317 - val_loss: 0.5460 - val_accuracy: 0.7346
Epoch 29/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7330 - val_loss: 0.5446 - val_accuracy: 0.7362
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7324 - val_loss: 0.5448 - val_accuracy: 0.7359
Epoch 31/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7317 - val_loss: 0.5426 - val_accuracy: 0.7367
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7314 - val_loss: 0.5438 - val_accuracy: 0.7359
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7328 - val_loss: 0.5439 - val_accuracy: 0.7357
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7318 - val_loss: 0.5445 - val_accuracy: 0.7362
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7312 - val_loss: 0.5446 - val_accuracy: 0.7375
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7325 - val_loss: 0.5436 - val_accuracy: 0.7367
Epoch 37/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5459 - accuracy: 0.7325 - val_loss: 0.5464 - val_accuracy: 0.7385
Epoch 38/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7321 - val_loss: 0.5448 - val_accuracy: 0.7370
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7319 - val_loss: 0.5425 - val_accuracy: 0.7378
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7322 - val_loss: 0.5440 - val_accuracy: 0.7372
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7326 - val_loss: 0.5424 - val_accuracy: 0.7375
Epoch 42/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5456 - accuracy: 0.7325 - val_loss: 0.5430 - val_accuracy: 0.7295
Epoch 43/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7307 - val_loss: 0.5429 - val_accuracy: 0.7367
Epoch 44/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7319 - val_loss: 0.5421 - val_accuracy: 0.7372
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7321 - val_loss: 0.5422 - val_accuracy: 0.7380
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7312 - val_loss: 0.5429 - val_accuracy: 0.7341
Epoch 47/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7320 - val_loss: 0.5426 - val_accuracy: 0.7372
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7334 - val_loss: 0.5421 - val_accuracy: 0.7362
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7329 - val_loss: 0.5438 - val_accuracy: 0.7365
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7325 - val_loss: 0.5412 - val_accuracy: 0.7370
Epoch 51/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7324 - val_loss: 0.5419 - val_accuracy: 0.7362
Epoch 52/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7314 - val_loss: 0.5426 - val_accuracy: 0.7378
Epoch 53/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7335 - val_loss: 0.5426 - val_accuracy: 0.7362
Epoch 54/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7325 - val_loss: 0.5411 - val_accuracy: 0.7367
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7336 - val_loss: 0.5426 - val_accuracy: 0.7370
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7322 - val_loss: 0.5414 - val_accuracy: 0.7367
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7323 - val_loss: 0.5418 - val_accuracy: 0.7372

Epoch 58/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7322 - val_loss: 0.5430 - val_accuracy: 0.7354
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7325 - val_loss: 0.5448 - val_accuracy: 0.7380
Epoch 60/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7328 - val_loss: 0.5418 - val_accuracy: 0.7365
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7323 - val_loss: 0.5418 - val_accuracy: 0.7344
Epoch 62/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7329 - val_loss: 0.5411 - val_accuracy: 0.7349
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7325 - val_loss: 0.5412 - val_accuracy: 0.7375
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7325 - val_loss: 0.5419 - val_accuracy: 0.7378
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7320 - val_loss: 0.5410 - val_accuracy: 0.7352
Epoch 66/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7326 - val_loss: 0.5412 - val_accuracy: 0.7367
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7317 - val_loss: 0.5432 - val_accuracy: 0.7310
Epoch 68/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7339 - val_loss: 0.5417 - val_accuracy: 0.7354
Epoch 69/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7316 - val_loss: 0.5438 - val_accuracy: 0.7365
Epoch 70/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7320 - val_loss: 0.5413 - val_accuracy: 0.7385
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7325 - val_loss: 0.5418 - val_accuracy: 0.7367
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7327 - val_loss: 0.5411 - val_accuracy: 0.7365
Epoch 73/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7324 - val_loss: 0.5421 - val_accuracy: 0.7362
Epoch 74/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7325 - val_loss: 0.5414 - val_accuracy: 0.7388
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7324 - val_loss: 0.5407 - val_accuracy: 0.7378
Epoch 76/100
519/684 [=====================>........] - ETA: 0s - loss: 0.5456 - accuracy: 0.7315

In [ ]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
from google.colab import files

nn.save('AlphabetSoupCharity.h5')
files.download('AlphabetSoupCharity.h5')